import type { Metadata } from "next";
import localFont from "next/font/local";

import "../styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { ThemeProvider } from "@/contexts/theme-provider";
import { Web3ModalProvider } from "@/contexts/web3-modal-provide";
import { Header } from "@/components/shared/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Web3ModalProvider>
            <Header />
            {children}
          </Web3ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
