name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0
      NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
      NEXT_PUBLIC_ENABLE_MAINNET: ${{ secrets.NEXT_PUBLIC_ENABLE_MAINNET }}
      NEXT_PUBLIC_ETHEREUM_URL_TRANSPORT: ${{ secrets.NEXT_PUBLIC_ETHEREUM_URL_TRANSPORT }}
      NEXT_PUBLIC_SEPOLIA_URL_TRANSPORT: ${{ secrets.NEXT_PUBLIC_SEPOLIA_URL_TRANSPORT }}
      NEXT_PUBLIC_LOTTERY_CONTRACT: ${{ secrets.NEXT_PUBLIC_LOTTERY_CONTRACT }}
      NEXT_PUBLIC_LOTTERY_TOKEN_CONTRACT: ${{ secrets.NEXT_PUBLIC_LOTTERY_TOKEN_CONTRACT }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: pnpm@9.9.0+sha512.60c18acd138bff695d339be6ad13f7e936eea6745660d4cc4a776d5247c540d0edee1a563695c183a66eb917ef88f2b4feb1fc25f32a7adcadc7aaf3438e99c1
          run_install: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm run build
      - run: pnpm run lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
